# Generated by Django 2.0.3 on 2018-04-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotID', models.IntegerField(default=0)),
                ('timeIn', models.DateTimeField()),
                ('timeOut', models.DateTimeField(null=True)),
            ],
        ),
    ]
